### ISSUE TITLE
Is the Slack Channel open to public?

### ISSUE THREAD

**Issue by PrestonII** [IBM/socket-io#3]
Trying to confirm that the slack channel mentioned on the README is open to the public? Would love to implement this in my project since the Ouobject library was just deprecated but wanted to get some feedback from the devs on this one

**Comment by cmuentes** [comment]
Yes - the Slack channel should be public.  If you are unable to connect let me know and I will get it opened up.

**Comment by cmuentes** [comment]
@PrestonII ☝️

**Comment by SamuelMeilleur** [comment]
@cmuentes Hi, the link only lets me sign in if I already have a guest account but doesn't let me create one.

**Comment by cmuentes** [comment]
@SamuelMeilleur I am investigating - it should be public and open!  However, doesn't Slack require you to have an account either way?  You may need to create a Slack account then you can join.  Try that and let me know, and in the mean time I will continue investigating.

**Comment by SamuelMeilleur** [comment]
@cmuentes Slack doesn't really have global accounts. You have have an account per workspace that can all be linked to the same email address. So I think I still need to register to your slack workspace but it's obviously blocked to email accounts that aren't from your organisation. I've never tried the invite guests feature but I think you have to send them individually unfortunately.

The two options I have when clicking the link are "Sign in with IBM W3id" and "I have a guest account".

**Comment by cmuentes** [comment]
@SamuelMeilleur Okay I will continue to investigate.  I submitted a support ticket to our internal Slack team and hopefully they will respond quickly.  In the mean time, if you have a question, go ahead and open a new ticket and I will respond.  Thanks!!
cc >> @barnysanchez

**Comment by SamuelMeilleur** [comment]
thanks

**Comment by PrestonII** [comment]
sorry about the delayed response @cmuentes - I'm essentially having the same issue as @SamuelMeilleur. Please let us know if/when your internal team gets back to you?

![image](https://user-images.githubusercontent.com/9745948/52282915-71259180-292f-11e9-94cd-b7f4fb43e3d2.png)

**Comment by cmuentes** [comment]
@PrestonII I am actually conversing with one of our executives on our internal Slack _right now_ about this very issue.  Stay tuned!

**Comment by cmuentes** [comment]
@PrestonII @SamuelMeilleur I've gotten internal approval to create a public Slack channel for this project.  I was notified it will take infrastructure ~3-5 business days to create the channel and as soon as it's available, I'll post it on this ticket and will update the `README.md` file as well.  Thanks for being patient!

**Comment by craftbyte** [comment]
Hey there @cmuentes, any updates on that?

**Comment by PhilippElhaus** [comment]
Also plenty of questions here from my end...would love to not have them but the documentation is very thin at this point. Promising project but ... :/

**Comment by Jameskmonger** [comment]
@cmuentes any news?

**Comment by AshotN** [comment]
This project seemed to show up out of nowhere, and then it's sole maintainer disappeared.
