### ISSUE TITLE
Need exemple

### ISSUE THREAD

**Issue by Elegary** [IBM/socket-io#5]
Can you post an exemple of code ?
I am unable to use your project because I don't understand everything :(

**Comment by cmuentes** [comment]
I am sorry somehow I didn't get notice of this ticket.  I will assemble an example this weekend and send over asap; thanks! @Elegary

**Comment by cmuentes** [comment]
I have added a sample usage to the `Readme.md` file at the root of this project; thanks! @Elegary

**Comment by AshotN** [comment]
Is it possible to get a couple use-case examples. I generally find those helpful, I really appreciate this project. Thank you :)
